<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vaultix.Shared\Vaultix.Shared.csproj" />
    <ProjectReference Include="..\Vaultix.Storage\Vaultix.Storage.csproj" />
  </ItemGroup>

</Project>
