<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vaultix.Core\Vaultix.Core.csproj" />
    <ProjectReference Include="..\Vaultix.Shared\Vaultix.Shared.csproj" />
  </ItemGroup>

</Project>
